<a class="btn btn-small"
	onclick="openViewDate(<?php echo $date->getID() ?>)"><i
	class="icon-eye-open"></i> </a>
<a class="btn btn-small"
	onclick="openAssignDateToSelf(<?php echo $date->getID() ?>)"><i
	class="icon-resize-small"></i> </a>
<a class="btn btn-small"
	onclick="openCalendarEntry(<?php echo $date->getID() ?>)"><i
	class="icon-calendar"></i> </a>
