<a class="btn btn-small"
	onclick="openViewDate(<?php echo $date->getID() ?>)"><i
	class="icon-eye-open"></i> </a>
<a class="btn btn-small"
	onClick="openCalendarEntry(<?php echo $date->getID() ?>)"><i
	class="icon-calendar"></i> </a>
<a class="btn btn-small"
	onClick="openEmailToParents(<?php echo $date->getID() ?>)"><i
	class="icon-envelope"></i> </a>
<a class="btn btn-small"
	onclick="openUnassignDate(<?php echo $date->getID() ?>)"><i
	class="icon-resize-full"></i> </a>
